### ISSUE TITLE
Yarn pnp nodeLinker does not work

### ISSUE THREAD

**Issue by yordis** [sheerlox/import-from-esm#80]
I am using `pnp` linker as follow:

- Node Version: `v20.10.0`

```yaml
# .yarnrc.yml
compressionLevel: mixed
defaultSemverRangePrefix: ''
enableGlobalCache: false
nodeLinker: pnp
yarnPath: .yarn/releases/yarn-4.0.2.cjs
```

I am using `import-from-esm` at https://github.com/straw-hat-team/nodejs-monorepo/tree/master/packages/%40straw-hat/openapi-web-sdk-generator

Here is the config:

```yaml
# .openapi-web-sdk-generatorrc.yaml
generators:
  - path: '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js'
    config:
      outputDir: 'src/lib/services/flashbot-api/operations'
  - path: '@straw-hat/openapi-web-sdk-generator/dist/generators/react-query-fetcher/index.js'
    config:
      outputDir: 'src/lib/services/flashbot-api/react-query'
      packageName: '../operations'

```

And the `package.json`

```json
{
  "packageManager": "yarn@4.0.2",
  "engines": {
    "node": "20.x"
  },
  "type": "module",
  "scripts": {
    "codegen:sdk": "sht-openapi-web-sdk-generator local --config='./openapi.json'"
  }
}
```

When I do `DEBUG=* yarn codegen:sdk`, I get the following outcome:

```
  @straw-hat/openapi-web-sdk-generator:helpers Configuration file /Users/ubi/Developer/myapp/.openapi-web-sdk-generatorrc.yaml loaded +0ms
  @straw-hat/openapi-web-sdk-generator:open-api-web-sdk-generator Loading Generator: @straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js +0ms
  import-from-esm Executing importFrom('/Users/ubi/Developer/myapp', '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js') +0ms
  import-from-esm '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js' is not a file module +0ms
  import-from-esm Trying to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js' from 'file:///Users/ubi/Developer/myapp/noop.js' +0ms
  import-from-esm Failed to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js' from 'file:///Users/ubi/Developer/myapp/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@straw-hat/openapi-web-sdk-generator' imported from /Users/ubi/Developer/myapp/noop.js +1ms
  import-from-esm Trying to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.js' from 'file:///Users/ubi/Developer/myapp/noop.js' +0ms
  import-from-esm Failed to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.js' from 'file:///Users/ubi/Developer/myapp/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@straw-hat/openapi-web-sdk-generator' imported from /Users/ubi/Developer/myapp/noop.js +1ms
  import-from-esm Trying to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.mjs' from 'file:///Users/ubi/Developer/myapp/noop.js' +0ms
  import-from-esm Failed to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.mjs' from 'file:///Users/ubi/Developer/myapp/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@straw-hat/openapi-web-sdk-generator' imported from /Users/ubi/Developer/myapp/noop.js +0ms
  import-from-esm Trying to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.cjs' from 'file:///Users/ubi/Developer/myapp/noop.js' +0ms
  import-from-esm Failed to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.cjs' from 'file:///Users/ubi/Developer/myapp/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@straw-hat/openapi-web-sdk-generator' imported from /Users/ubi/Developer/myapp/noop.js +0ms
  import-from-esm Trying to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.json' from 'file:///Users/ubi/Developer/myapp/noop.js' +0ms
  import-from-esm Failed to resolve '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.json' from 'file:///Users/ubi/Developer/myapp/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@straw-hat/openapi-web-sdk-generator' imported from /Users/ubi/Developer/myapp/noop.js +1ms
  import-from-esm Cannot find module '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js' +0ms
    Error: Failed to load configuration file @straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js.
    Cannot find module '@straw-hat/openapi-web-sdk-generator/dist/generators/fetcher/index.js'
```

If I change the linker to `node-modules` then it works just fine, so something is broken using `pnp` linker and this package.

Any thoughts?!
